[package]
name = "renv"
version = "0.2.0"
authors = ["Chris Dawes <cmsd2@cantab.net>"]
license = "MIT/Apache-2.0"
description = "Environment variable loader"
repository = "https://github.com/cmsd2/renv"

[dependencies]
clap = "2.1.2"
java-properties = "0.1.1"

[features]
unstable = []
